name = "Insomnia"
author = "dylanxyz"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e9f123f34fdc8d9e5b2a0b249f99c064e2c0f5a90b1c74141140b3ed249dafd"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
