name = "Insomnia"
author = "dylanxyz"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fe7a070bc94f5cc3f5e31739e3fc88dbacf0bd0b5480cb033ee97e7d7623387"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
