name = "Insomnia"
author = "dylanxyz"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78f646b44c4f4c589a6b1cc6dd2fa2432b29d454f87c9862c1443139cdbee6ee"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
