import * as tags from "@lib/data/tags.ts"
import { categoryTag } from "@root/insomnia/utils.ts"
import { namespace } from "@lib/core/utils.ts"

const category = namespace("category")

categoryTag(category.engineering, {
    title : "Engenharia",
    icon  : "create:item/goggles"
})

tags.item(category.engineering, [
    "minecraft:redstone",
    "minecraft:repeater",
    "minecraft:comparator",
    "minecraft:lever",
    "minecraft:sculk_sensor",
    "minecraft:calibrated_sculk_sensor",
    "minecraft:tripwire_hook",
    "minecraft:daylight_detector",
    "minecraft:piston",
    "minecraft:sticky_piston",
    "minecraft:dispenser",
    "minecraft:dropper",
    "minecraft:hopper",
    "minecraft:observer",
])

/// supplementaries ---------------------------------------------
export const supplementaries = tags.item(category.engineering, [
    "supplementaries:cog_block",
    "supplementaries:crank",
    "supplementaries:relayer",
    "supplementaries:redstone_illuminator",
    "supplementaries:pulley_block",
])

/// create ---------------------------------------------
export const create = tags.item(category.engineering, [
    "create:linked_controller",
    "create:shaft",
    "create:cogwheel",
    "create:large_cogwheel",
    "create:gearbox",
    "create:vertical_gearbox",
    "create:clutch",
    "create:gearshift",
    "create:encased_chain_drive",
    "create:adjustable_chain_gearshift",
    "create:belt_connector",
    "create:chain_conveyor",
    "create:water_wheel",
    "create:large_water_wheel",
    "create:encased_fan",
    "create:nozzle",
    "create:turntable",
    "create:hand_crank",
    "create:millstone",
    "create:crushing_wheel",
    "create:mechanical_press",
    "create:mechanical_mixer",
    "create:basin",
    "create:empty_blaze_burner",
    "create:blaze_burner",
    "create:depot",
    "create:weighted_ejector",
    "create:chute",
    "create:smart_chute",
    "create:speedometer",
    "create:stressometer",
    "create:fluid_pipe",
    "create:mechanical_pump",
    "create:smart_fluid_pipe",
    "create:fluid_valve",
    "create:copper_valve_handle",
    "create:fluid_tank",
    "create:hose_pulley",
    "create:item_drain",
    "create:spout",
    "create:portable_fluid_interface",
    "create:steam_engine",
    "create:steam_whistle",
    "create:mechanical_piston",
    "create:sticky_mechanical_piston",
    "create:piston_extension_pole",
    "create:gantry_carriage",
    "create:gantry_shaft",
    "create:windmill_bearing",
    "create:mechanical_bearing",
    "create:clockwork_bearing",
    "create:rope_pulley",
    "create:elevator_pulley",
    "create:linear_chassis",
    "create:secondary_linear_chassis",
    "create:radial_chassis",
    "create:sticker",
    "create:contraption_controls",
    "create:mechanical_drill",
    "create:mechanical_saw",
    "create:deployer",
    "create:portable_storage_interface",
    "create:redstone_contact",
    "create:mechanical_harvester",
    "create:mechanical_plough",
    "create:mechanical_roller",
    "create:sail_frame",
    "create:white_sail",
    "create:andesite_casing",
    "create:brass_casing",
    "create:copper_casing",
    "create:mechanical_crafter",
    "create:sequenced_gearshift",
    "create:flywheel",
    "create:rotation_speed_controller",
    "create:mechanical_arm",
    "create:andesite_funnel",
    "create:brass_funnel",
    "create:andesite_tunnel",
    "create:brass_tunnel",
    "create:content_observer",
    "create:stockpile_switch",
    "create:packager",
    "create:repackager",
    "create:package_frogport",
    "create:stock_link",
    "create:stock_ticker",
    "create:redstone_requester",
    "create:factory_gauge",
    "create:display_link",
    "create:display_board",
    "create:nixie_tube",
    "create:redstone_link",
    "create:analog_lever",
    "create:placard",
    "create:pulse_repeater",
    "create:pulse_extender",
    "create:pulse_timer",
    "create:powered_latch",
    "create:powered_toggle_latch",
])

/// createdieselgenerators ---------------------------------------------
export const createdieselgenerators = tags.item(category.engineering, [
    "createdieselgenerators:diesel_engine",
    "createdieselgenerators:large_diesel_engine",
    "createdieselgenerators:huge_diesel_engine",
    "createdieselgenerators:pumpjack_hole",
    "createdieselgenerators:pumpjack_bearing",
    "createdieselgenerators:pumpjack_crank",
    "createdieselgenerators:pumpjack_head",
    "createdieselgenerators:canister",
    "createdieselgenerators:oil_barrel",
    "createdieselgenerators:basin_lid",
    "createdieselgenerators:bulk_fermenter",
    "createdieselgenerators:burner",
    "createdieselgenerators:chemical_turret",
])

/// petrolsparts ---------------------------------------------
export const petrolsparts = tags.item(category.engineering, [
    "petrolsparts:coaxial_gear",
    "petrolsparts:large_coaxial_gear",
    "petrolsparts:double_cardan_shaft",
    "petrolsparts:differential",
    "petrolsparts:planetary_gearset",
    "petrolsparts:colossal_cogwheel",
    "petrolsparts:pneumatic_tube",
    "petrolsparts:hydraulic_transmission",
])
