items {
    "metal_works:bronze_axe"=250
    "metal_works:bronze_pickaxe"=250
    "metal_works:bronze_shovel"=250
    "metal_works:bronze_hoe"=250
    "metal_works:bronze_sword"=250
}

items {
    "metal_works:tin_axe"=32
    "metal_works:tin_pickaxe"=32
    "metal_works:tin_shovel"=32
    "metal_works:tin_hoe"=32
    "metal_works:tin_sword"=32
}
