enable_system_global_packs = false

[resourcepacks]
required = [
    "packs/bundled/",
    "packs/resources/"
]

[datapacks]
required = [
    "resourcepacks/",
    "packs/bundled/",
    "packs/datpacks/"
]

optional = []
