# Visit https://github.com/gizmo-ds/key-binding-hider-mod for detailed configuration options.

# Set the key bindings to unknown
SetKeyBindingToUnknown = false

# List of key bindings to hide
KeyBindings = [
    "key_key.fancytoasts.config_menu",
    "key_key.entityculling.toggle",
    "key_key.modernfix.config",
    "key_key.oneenoughitem.open_editor",
    "key_key.clienttweaks.hideOffhandItem",
    "key_key.clienttweaks.disableStepAssist",
    "key_key.clienttweaks.disableLogStripping",
    "key_key.immersiveoverlays.toggle",
    "key_key.immersiveoverlays.settings",
    "key_key.open_muffler_gui",
    "key_key.nfo.copycats.fill_copycat",
    "key_key.ride.zoom",
    "key_key.irons_spellbooks.spell_quick_cast_1",
    "key_key.irons_spellbooks.spell_quick_cast_2",
    "key_key.irons_spellbooks.spell_quick_cast_3",
    "key_key.irons_spellbooks.spell_quick_cast_4",
    "key_key.irons_spellbooks.spell_quick_cast_5",
    "key_key.irons_spellbooks.spell_quick_cast_6",
    "key_key.irons_spellbooks.spell_quick_cast_7",
    "key_key.irons_spellbooks.spell_quick_cast_8",
    "key_key.irons_spellbooks.spell_quick_cast_9",
    "key_key.irons_spellbooks.spell_quick_cast_10",
    "key_key.irons_spellbooks.spell_quick_cast_11",
    "key_key.irons_spellbooks.spell_quick_cast_12",
    "key_key.irons_spellbooks.spell_quick_cast_13",
    "key_key.irons_spellbooks.spell_quick_cast_14",
    "key_key.irons_spellbooks.spell_quick_cast_15",
    "key_key.curios.open.desc",
    "key_key_portable_blueprints.key_mapping.move_origin.up",
    "key_key_portable_blueprints.key_mapping.move_origin.down",
    "key_key_portable_blueprints.key_mapping.move_origin.px",
    "key_key_portable_blueprints.key_mapping.move_origin.nx",
    "key_key_portable_blueprints.key_mapping.move_origin.pz",
    "key_key_portable_blueprints.key_mapping.move_origin.nz",
    "key_key_Import Packs (Developers Only)",

    "key_key.mdf.z_action",
    "key_key.mdf.x_action",
    "key_key.mdf.c_action",
    "key_key.mdf.v_action",
    "key_key.mdf.r_action",
    "key_key.mdf.blessing_menu",

    "key_key.jade.config",
    "key_key.jade.show_overlay",
    "key_key.jade.toggle_liquid",
    "key_key.jade.show_recipes",
    "key_key.jade.show_uses",
    "key_key.jade.narrate",
    "key_key.jade.show_details",

    "key_key.jei.toggleCheatModeConfigButton",
    "key_key.jei.showRecipe",
    "key_key.jei.copy",
    "key_key.jei.bookmark",
    "key_key.jei.toggleWildcardHideIngredient",
    "key_key.jei.transferRecipeBookmark",
    "key_key.jei.previousSearch",
    "key_key.jei.previousCategory",
    "key_key.jei.toggleEditMode",
    "key_key.jei.toggleOverlay",
    "key_key.jei.cheatItemStack2",
    "key_key.jei.closeRecipeGui",
    "key_key.jei.showRecipe2",
    "key_key.jei.maxTransferRecipeBookmark",
    "key_key.jei.toggleBookmarkOverlay",
    "key_key.jei.cheatOneItem2",
    "key_key.jei.previousRecipePage",
    "key_key.jei.nextCategory",
    "key_key.jei.showUses",
    "key_key.jei.nextPage",
    "key_key.jei.nextRecipePage",
    "key_key.jei.previousPage",
    "key_key.jei.cheatOneItem",
    "key_key.jei.focusSearch",
    "key_key.jei.toggleCheatMode",
    "key_key.jei.toggleHideIngredient",
    "key_key.jei.recipeBack",
    "key_key.jei.showUses2",
    "key_key.jei.nextSearch",
    "key_key.jei.cheatItemStack",
    "key_key.jei.clearSearchBar",

    "key_gui.xaero_minimap_settings",
    "key_gui.xaero_minimap_server_profiles",
    "key_gui.xaero_zoom_in",
    "key_gui.xaero_zoom_out",
    "key_gui.xaero_enlarge_map",
    "key_gui.xaero_toggle_map",
    "key_gui.xaero_toggle_map_waypoints",
    "key_gui.xaero_toggle_slime",
    "key_gui.xaero_toggle_grid",
    "key_gui.xaero_instant_waypoint",
    "key_gui.xaero_switch_waypoint_set",
    "key_gui.xaero_display_all_sets",
    "key_gui.xaero_toggle_light_overlay",
    "key_gui.xaero_toggle_entity_radar",
    "key_gui.xaero_reverse_entity_radar",
    "key_gui.xaero_toggle_manual_cave_mode",
    "key_gui.xaero_alternative_list_players",
    "key_gui.xaero_toggle_tracked_players_on_map",
    "key_gui.xaero_toggle_tracked_players_in_world",
    "key_gui.xaero_toggle_pac_chunk_claims",
]
